klee: add missing include
tools/klee/main.cpp:271:24: error: 'llvm::sys::path' has not been declared

Signed-off-by: Marek Chalupa <mchqwerty@gmail.com>